import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { execFileSync } from "child_process";
import { PingletConfig, cliPath, saveConfig } from "../config";
import { loadFeedMessages } from "../cache";
import { formatPing } from "../render";
import { FeedMessage } from "../types";

const CLAUDE_DIR = path.join(os.homedir(), ".claude");
const SETTINGS_PATH = path.join(CLAUDE_DIR, "settings.json");
const COMMANDS_DIR = path.join(CLAUDE_DIR, "commands");
const COMMAND_PATH = path.join(COMMANDS_DIR, "pinglet.md");
const COMMAND_MARKER = "generated by pinglet";

/**
 * Claude Adapter.
 * Claude Code의 statusLine hook에 `pinglet statusline`을 연결한다.
 * - statusline은 UI 영역이므로 LLM context에 전혀 들어가지 않는다 (Zero Token).
 * - Claude가 Thinking/Working 중일 때 status 영역에 Ping 메시지가 보인다.
 */
export function detectClaude(): boolean {
  if (fs.existsSync(CLAUDE_DIR)) return true;
  try {
    execFileSync(process.platform === "win32" ? "where" : "which", ["claude"], {
      stdio: "ignore",
    });
    return true;
  } catch {
    return false;
  }
}

function statusLineCommand(): string {
  return `node "${cliPath()}" statusline`;
}

/**
 * statusline 이벤트 트리거는 유휴 세션에서 멈추므로(새 메시지가 있어야 재실행),
 * 유휴 pane이 옛 온라인 터미널 수를 계속 표시하지 않게 고정 주기(초)로도 재실행한다.
 */
const STATUSLINE_REFRESH_INTERVAL_S = 30;

/** 예전 버전이 등록한 hook entry인지 식별 (command에 hook-prompt 포함 여부). */
function isPingletHookEntry(entry: HookEntry): boolean {
  return (
    entry.hooks?.some(
      (h) => typeof h.command === "string" && h.command.includes("hook-prompt"),
    ) ?? false
  );
}

/**
 * `/pinglet` 인라인 bash를 허용하는 settings.json 권한 규칙.
 * auto 권한 모드에서는 allow 규칙에 없는 Bash 명령을 LLM 분류기가 심사하는데,
 * 메시지 내용("~해라" 같은 명령문)에 따라 차단될 수 있어 규칙으로 명시한다.
 */
function postPermissionRule(): string {
  return `Bash(node "${cliPath()}" post:*)`;
}

/** Pinglet이 등록한 post 권한 규칙인지 식별 (경로가 바뀐 옛 규칙 포함). */
function isPingletPermissionRule(rule: string): boolean {
  return (
    rule === postPermissionRule() ||
    (rule.startsWith('Bash(node "') &&
      rule.includes("pinglet") &&
      rule.endsWith('" post:*)'))
  );
}

/**
 * `/pinglet` slash command 파일을 설치한다.
 * 등록 자체는 command 안의 인라인 bash(`!` 실행)가 수행하고,
 * 모델은 그 결과 한 줄만 전달하므로 토큰 사용이 매우 적다.
 * $ARGUMENTS는 따옴표로 감싸 메시지 전체가 하나의 인자로 전달되게 한다
 * (메시지 속 단어가 셸/CLI 플래그로 해석되는 것을 방지).
 */
function installSlashCommand(): void {
  fs.mkdirSync(COMMANDS_DIR, { recursive: true });
  fs.writeFileSync(
    COMMAND_PATH,
    `---
description: 메시지를 Pinglet에 등록해 다른 개발자들의 터미널에 표시
allowed-tools: Bash(node:*)
---
<!-- ${COMMAND_MARKER} -->

등록 결과: !\`node "${cliPath()}" post --quiet "$ARGUMENTS"\`

위 등록 결과 줄을 아무것도 덧붙이거나 바꾸지 말고 그대로 한 줄만 출력하세요.
다른 설명, 안내, 작업을 일절 하지 마세요.
`,
  );
}

/** Pinglet이 생성한 command 파일만 삭제한다 (마커로 확인). */
function uninstallSlashCommand(): boolean {
  try {
    if (!fs.readFileSync(COMMAND_PATH, "utf8").includes(COMMAND_MARKER)) {
      return false;
    }
    fs.unlinkSync(COMMAND_PATH);
    return true;
  } catch {
    return false;
  }
}

/** 예전 버전이 등록한 UserPromptSubmit hook을 정리한다 (hook 방식은 폐기됨). */
function uninstallPromptHook(settings: ClaudeSettings): boolean {
  const entries = settings.hooks?.UserPromptSubmit;
  if (!entries?.some(isPingletHookEntry)) return false;

  const remaining = entries.filter((entry) => !isPingletHookEntry(entry));
  if (remaining.length > 0) {
    settings.hooks!.UserPromptSubmit = remaining;
  } else {
    delete settings.hooks!.UserPromptSubmit;
    if (Object.keys(settings.hooks!).length === 0) delete settings.hooks;
  }
  return true;
}

interface SpinnerTipsOverride {
  excludeDefault?: boolean;
  tips: string[];
}

interface SpinnerVerbs {
  mode: "append" | "replace";
  verbs: string[];
}

interface HookEntry {
  matcher?: string;
  hooks?: Array<{ type?: string; command?: string; [key: string]: unknown }>;
  [key: string]: unknown;
}

interface ClaudeSettings {
  statusLine?: { type?: string; command?: string; [key: string]: unknown };
  spinnerTipsOverride?: SpinnerTipsOverride;
  spinnerVerbs?: SpinnerVerbs;
  hooks?: Record<string, HookEntry[]>;
  permissions?: { allow?: string[]; [key: string]: unknown };
  [key: string]: unknown;
}

/** Pinglet이 쓴 항목인지 식별하는 마커. uninstall 시 사용자 것과 구분한다. */
const PINGLET_TIP_MARKER = "​"; // zero-width space (항목 앞에 붙임)
const MAX_VERBS = 30;
/** spinner 한 줄에 "(27s · ↓ 1.0k tokens)" 등이 뒤에 붙으므로 여유를 둔다. */
const MAX_VERB_LEN = 60;

function readSettings(): ClaudeSettings {
  return readSettingsWithMtime().settings;
}

function settingsMtimeMs(): number | null {
  try {
    return fs.statSync(SETTINGS_PATH).mtimeMs;
  } catch {
    return null; // 파일 없음
  }
}

function readSettingsWithMtime(): {
  settings: ClaudeSettings;
  mtimeMs: number | null;
} {
  const mtimeMs = settingsMtimeMs();
  try {
    return {
      settings: JSON.parse(
        fs.readFileSync(SETTINGS_PATH, "utf8"),
      ) as ClaudeSettings,
      mtimeMs,
    };
  } catch {
    return { settings: {}, mtimeMs };
  }
}

/**
 * mtime이 읽던 시점 그대로일 때만 쓴다 — 변경이 감지되면 false를 돌려주고
 * 호출부가 다시 읽어 재적용한다. Claude Code 자신도 이 파일을 쓰기 때문에,
 * 그 사이의 변경을 우리 스냅샷으로 덮어써 사용자 설정을 유실하면 안 된다.
 */
function writeSettings(
  settings: ClaudeSettings,
  expectedMtimeMs: number | null,
): boolean {
  fs.mkdirSync(CLAUDE_DIR, { recursive: true });
  if (settingsMtimeMs() !== expectedMtimeMs) return false;
  // settings.json은 Claude Code가 수시로 읽는 파일이라 tmp+rename으로 원자적으로 쓴다.
  // tmp 이름에 pid를 붙여 프로세스마다 다르게 만든다 — 여러 세션의 statusline이
  // 동시에 돌면 같은 tmp에 겹쳐 쓰게 되고, writeFileSync는 truncate 후 쓰기라
  // 짧은 내용 뒤에 긴 내용의 꼬리가 남은 채로 rename 되어 settings.json이 깨진다.
  // rename 자체는 tmp 이름과 무관하게 원자적이라 이것만으로 충분하다.
  const tmp = `${SETTINGS_PATH}.pinglet-tmp.${process.pid}`;
  try {
    fs.writeFileSync(tmp, JSON.stringify(settings, null, 2) + "\n");
    fs.renameSync(tmp, SETTINGS_PATH);
  } catch (error) {
    // rename 전에 실패하면 tmp가 남는다 — 이름이 pid별로 달라 방치하면 쌓인다.
    try {
      fs.unlinkSync(tmp);
    } catch {
      // 이미 없으면 무시
    }
    throw error;
  }
  return true;
}

function isPingletTip(tip: string): boolean {
  return tip.startsWith(PINGLET_TIP_MARKER);
}

function buildPingletVerbs(messages: FeedMessage[]): string[] {
  return messages.slice(0, MAX_VERBS).map((message) => {
    let line = formatPing(message);
    if (line.length > MAX_VERB_LEN) {
      line = line.slice(0, MAX_VERB_LEN - 1) + "…";
    }
    return PINGLET_TIP_MARKER + line;
  });
}

/**
 * 예전 버전이 spinnerTipsOverride에 등록해 둔 Pinglet tips를 정리한다.
 * (tips는 "└ Tip: ..." 줄로 그려져서 verb 교체 방식으로 옮겼다.)
 */
function cleanupSpinnerTips(
  settings: ClaudeSettings,
  config: PingletConfig,
): boolean {
  const override = settings.spinnerTipsOverride;
  if (!override?.tips?.some(isPingletTip)) return false;

  const adapter = config.adapters.claude;
  const backup = adapter?.spinnerTipsBackup;
  const userTips = override.tips.filter((tip) => !isPingletTip(tip));
  if (backup) {
    settings.spinnerTipsOverride = backup as SpinnerTipsOverride;
  } else if (userTips.length > 0) {
    settings.spinnerTipsOverride = { ...override, tips: userTips };
  } else {
    delete settings.spinnerTipsOverride;
  }
  if (adapter?.spinnerTipsBackup !== undefined) {
    delete adapter.spinnerTipsBackup;
    saveConfig(config);
  }
  return true;
}

/**
 * Claude Code spinner verb("Befuddling…" 자리)에 메시지 **하나만** armed한다.
 * pool을 1개로 유지해야 "spinner가 돌았다 = 이 메시지가 표시됐다"가 확정되고,
 * cost 델타 기반 노출 측정(statusline)이 정확해진다. 설정은 핫리로드된다.
 * message가 null이면 우리 verb를 걷어내고 기본 spinner로 되돌린다.
 * 마커가 붙은 항목만 Pinglet 소유로 보고 교체하며, 사용자 verb는 유지한다.
 */
export function armSpinnerMessage(
  config: PingletConfig,
  message: FeedMessage | null,
): boolean {
  const adapter = config.adapters.claude;
  if (!adapter) return false;

  // 읽기~쓰기 사이에 다른 프로세스(Claude Code 등)가 파일을 바꿨으면
  // writeSettings가 거부하므로, 다시 읽어 재적용한다.
  for (let attempt = 0; attempt < 3; attempt++) {
    const { settings, mtimeMs } = readSettingsWithMtime();
    cleanupSpinnerTips(settings, config);

    const existing = settings.spinnerVerbs;
    const existingVerbs = existing?.verbs ?? [];

    // 사용자가 원래 갖고 있던 spinnerVerbs는 최초 1회 백업해 두고 uninstall 시 복원한다.
    const isOurs = existingVerbs.some(isPingletTip);
    if (existing && !isOurs && adapter.spinnerVerbsBackup === undefined) {
      adapter.spinnerVerbsBackup = existing;
      saveConfig(config);
    }

    const userVerbs = existingVerbs.filter((verb) => !isPingletTip(verb));
    const pingletVerbs = message ? buildPingletVerbs([message]) : [];

    // armed할 메시지가 없으면 spinner를 기본 상태로 되돌린다.
    if (pingletVerbs.length === 0) {
      if (!isOurs) return false;
      const backup = adapter.spinnerVerbsBackup;
      if (backup) {
        settings.spinnerVerbs = backup as SpinnerVerbs;
      } else if (userVerbs.length > 0) {
        settings.spinnerVerbs = { ...existing!, verbs: userVerbs };
      } else {
        delete settings.spinnerVerbs;
      }
      if (writeSettings(settings, mtimeMs)) {
        // 쓰기가 확정된 뒤에만 백업을 소비한다 (실패 시 백업 유실 방지).
        if (backup) {
          delete adapter.spinnerVerbsBackup;
          saveConfig(config);
        }
        return false;
      }
      continue;
    }

    const next = [...userVerbs, ...pingletVerbs];
    // 같은 메시지를 다시 armed하는 경우 파일 쓰기를 생략한다 (300ms 렌더링 경로 보호).
    if (
      existing?.mode === "replace" &&
      existingVerbs.length === next.length &&
      existingVerbs.every((v, i) => v === next[i])
    ) {
      return true;
    }

    settings.spinnerVerbs = { mode: "replace", verbs: next };
    if (writeSettings(settings, mtimeMs)) return true;
  }
  // 계속 충돌하면 이번 tick은 건너뛴다 — 다음 statusline tick에서 재시도된다.
  return false;
}

/** doctor용: spinner verb로 등록된 Pinglet 메시지 개수. */
export function spinnerVerbsStatus(): { count: number } {
  const settings = readSettings();
  const verbs = settings.spinnerVerbs?.verbs ?? [];
  return { count: verbs.filter(isPingletTip).length };
}

export function isClaudeIntegrationInstalled(): boolean {
  const settings = readSettings();
  return settings.statusLine?.command?.includes("pinglet") ?? false;
}

export function installClaudeIntegration(
  config: PingletConfig,
  options: { force?: boolean } = {},
): { ok: boolean; reason?: string; needsForce?: boolean } {
  for (let attempt = 0; attempt < 3; attempt++) {
    const { settings, mtimeMs } = readSettingsWithMtime();
    const existing = settings.statusLine;

    const isOurs = existing?.command?.includes("pinglet");
    if (existing && !isOurs && !options.force) {
      // needsForce: 호출부(install 커맨드)가 대화형이면 사용자에게 물어보고
      // force로 재시도할 수 있다.
      return {
        ok: false,
        needsForce: true,
        reason:
          "기존 statusLine 설정이 있습니다 (백업 후 교체하려면 --force).",
      };
    }

    config.adapters.claude = {
      // 재설치 시 기존 백업(spinnerVerbsBackup 등)이 날아가지 않게 유지한다.
      ...config.adapters.claude,
      installedAt: new Date().toISOString(),
      settingsPath: SETTINGS_PATH,
      // 사용자의 기존 설정은 백업해 두고 uninstall 시 복원한다.
      ...(existing && !isOurs && { statusLineBackup: existing }),
    };
    saveConfig(config);

    settings.statusLine = {
      type: "command",
      command: statusLineCommand(),
      refreshInterval: STATUSLINE_REFRESH_INTERVAL_S,
    };
    uninstallPromptHook(settings); // 구버전 hook 방식 흔적 정리

    // /pinglet 인라인 bash가 auto 모드 분류기에 막히지 않도록 allow 규칙 등록.
    // 경로가 바뀐(예: node 버전 업) 옛 규칙은 정리하고 현재 규칙 하나만 둔다.
    const permissions = (settings.permissions ??= {});
    const allow = (permissions.allow ??= []);
    const kept = allow.filter((rule) => !isPingletPermissionRule(rule));
    permissions.allow = [...kept, postPermissionRule()];

    if (!writeSettings(settings, mtimeMs)) continue; // 다른 프로세스와 충돌 → 재읽기
    installSlashCommand();

    // spinner verb는 로컬 캐시에 실제 feed가 있을 때만 채운다. 없으면 기본 spinner 유지.
    armSpinnerMessage(config, loadFeedMessages()[0] ?? null);
    return { ok: true };
  }
  return {
    ok: false,
    reason:
      "settings.json이 계속 변경되고 있어 설치하지 못했습니다. 잠시 후 다시 시도하세요.",
  };
}

export function uninstallClaudeIntegration(config: PingletConfig): boolean {
  let settingsChanged = false;

  for (let attempt = 0; attempt < 3; attempt++) {
    const { settings, mtimeMs } = readSettingsWithMtime();
    settingsChanged = false;

    if (settings.statusLine?.command?.includes("pinglet")) {
      const backup = config.adapters.claude?.statusLineBackup;
      if (backup) {
        settings.statusLine = backup as ClaudeSettings["statusLine"];
      } else {
        delete settings.statusLine;
      }
      settingsChanged = true;
    }

    if (cleanupSpinnerTips(settings, config)) {
      settingsChanged = true;
    }

    if (uninstallPromptHook(settings)) {
      settingsChanged = true;
    }

    const allow = settings.permissions?.allow;
    if (allow?.some(isPingletPermissionRule)) {
      const kept = allow.filter((rule) => !isPingletPermissionRule(rule));
      if (kept.length > 0) {
        settings.permissions!.allow = kept;
      } else {
        delete settings.permissions!.allow;
        if (Object.keys(settings.permissions!).length === 0) {
          delete settings.permissions;
        }
      }
      settingsChanged = true;
    }

    const verbs = settings.spinnerVerbs;
    if (verbs?.verbs?.some(isPingletTip)) {
      const verbsBackup = config.adapters.claude?.spinnerVerbsBackup;
      const userVerbs = verbs.verbs.filter((verb) => !isPingletTip(verb));
      if (verbsBackup) {
        settings.spinnerVerbs = verbsBackup as SpinnerVerbs;
      } else if (userVerbs.length > 0) {
        settings.spinnerVerbs = { ...verbs, verbs: userVerbs };
      } else {
        delete settings.spinnerVerbs;
      }
      settingsChanged = true;
    }

    if (!settingsChanged) break;
    if (writeSettings(settings, mtimeMs)) break; // 충돌 시 재읽기 후 재적용
  }

  const commandRemoved = uninstallSlashCommand();

  if (config.adapters.claude) {
    delete config.adapters.claude;
    saveConfig(config);
  }
  return settingsChanged || commandRemoved;
}
